import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
type Ingredient={id:string;name:string;amount:string;color:string};
type Hooks={select:(id:string)=>void;move:(id:string)=>void;ready?:()=>void;error?:(message:string)=>void};
export type Kitchen=ReturnType<typeof createKitchen>;
export function createKitchen(host:HTMLDivElement,ingredients:Ingredient[],hooks:Hooks){
const scene=new THREE.Scene();scene.background=new THREE.Color('#dbe5dc');
const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(0,12,14);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.5,0);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=38;controls.maxPolarAngle=Math.PI*.47;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};controls.enablePan=false;
scene.add(new THREE.HemisphereLight('#fffaf0','#596e4f',2.7));const sun=new THREE.DirectionalLight('#fff4d5',4);sun.position.set(-5,12,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:8,bottom:-8});sun.shadow.bias=-.001;scene.add(sun);
const materials:THREE.Material[]=[],geometries:THREE.BufferGeometry[]=[];
function mat(color:string,metalness=0,roughness=.7){const m=new THREE.MeshStandardMaterial({color,metalness,roughness});materials.push(m);return m}
const wood=mat('#ae7950'),edge=mat('#815136'),top=mat('#ecdfbb'),green=mat('#244f3c'),metal=mat('#99a6a0',.6,.3),dark=mat('#26342f'),white=mat('#fff7e7'),water=mat('#abcdda');
function mesh(geo:THREE.BufferGeometry,m:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){geometries.push(geo);const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(w:number,h:number,d:number,m:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),m,parent,x,y,z)}
function ell(w:number,h:number,d:number,m:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){const o=mesh(new THREE.SphereGeometry(1,16,10),m,parent,x,y,z);o.scale.set(w,h,d);return o}
function cyl(rt:number,rb:number,h:number,m:THREE.Material,parent:THREE.Object3D,x=0,y=0,z=0){return mesh(new THREE.CylinderGeometry(rt,rb,h,40),m,parent,x,y,z)}
box(200,.1,200,mat('#bbcdbc'),scene,0,-2.25,0);box(10.4,1.8,7.6,green,scene,0,-1.15,0);box(10.8,.24,8,edge,scene,0,-.15,0);box(10.8,.19,8,top,scene,0,.045,0);
for(let i=-4;i<=4;i+=2){box(1.88,1.38,.04,mat('#315b46'),scene,i,-1,3.83);box(.42,.045,.085,mat('#b9ba8d',.5),scene,i,-.44,3.88)}
box(9.5,.08,3.65,wood,scene,0,.18,1.59);for(let i=0;i<5;i++)box(9.3,.002,.013,edge,scene,0,.224,i*.67+.24);
box(4.3,.15,2.4,dark,scene,-2.55,.25,-2);
for(const x of [-3.65,-1.45]){const ring=mesh(new THREE.TorusGeometry(.76,.055,8,48),metal,scene,x,.345,-2);ring.rotation.x=Math.PI/2;for(let s=-1;s<=1;s+=2)box(.1,.1,1.68,dark,scene,x+s*.35,.38,-2)}
const pot=new THREE.Group();pot.position.set(-3.65,.42,-2);scene.add(pot);cyl(.73,.59,.62,metal,pot,0,.31,0);cyl(.65,.65,.025,water,pot,0,.63,0);for(const x of [-.87,.87])box(.34,.14,.2,dark,pot,x,.4,0);
const potFill=cyl(.62,.62,.03,white,pot,0,.65,0);potFill.visible=false;
const pan=new THREE.Group();pan.position.set(-1.4,.45,-2);scene.add(pan);cyl(.89,.70,.17,dark,pan,0,.06,0);box(.2,.12,1.2,dark,pan,0,.12,1.08);const panFill=cyl(.70,.70,.025,mat('#b32f17'),pan,0,.16,0);panFill.visible=false;
const plate=new THREE.Group();plate.position.set(2.7,.22,-1.8);scene.add(plate);cyl(1.53,1.36,.1,white,plate,0,.06,0);const pr=mesh(new THREE.TorusGeometry(1.42,.095,10,64),white,plate,0,.12,0);pr.rotation.x=Math.PI/2;
const leaf=ell(1.29,.018,1.16,mat('#31751d'),plate,0,.13,0);
const prepared=new THREE.Group();scene.add(prepared);prepared.position.set(0,.25,1.2);prepared.visible=false;
const cucumberMat=mat('#5d963d'),cucumberInside=mat('#d2e598');
const wholeCucumber=ell(.18,.16,.65,cucumberMat,prepared,0,.17,0);
const slices:THREE.Group[]=[];for(let i=0;i<4;i++){const g=new THREE.Group();g.position.set(-.60+i*.4,.08,.1);prepared.add(g);cyl(.20,.20,.10,cucumberMat,g);cyl(.175,.175,.01,cucumberInside,g,0,.055,0);g.visible=false;slices.push(g)}
const spoon=box(.08,.06,1.3,wood,pan,.12,.42,.26);spoon.rotation.y=.7;spoon.visible=false;
const panBits=new THREE.Group();pan.add(panBits);panBits.visible=false;for(let i=0;i<20;i++){const a=i*2.4,r=.56*Math.sqrt(i/20);ell(.10,.035,.035,mat('#c58b49'),panBits,r*Math.cos(a),.20,r*Math.sin(a))}
const eggs=new THREE.Group();pot.add(eggs);eggs.visible=false;ell(.19,.17,.19,white,eggs,-.23,.66,0);ell(.19,.17,.19,white,eggs,.23,.66,0);
const flame=mesh(new THREE.TorusGeometry(.62,.07,8,48),new THREE.MeshBasicMaterial({color:'#ed9b2b'}),scene,-3.65,.40,-2);materials.push(flame.material);flame.rotation.x=Math.PI/2;flame.visible=false;
const steam=new THREE.Group();scene.add(steam);for(let i=0;i<10;i++){const m=new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.3,depthWrite:false});materials.push(m);ell(.10,.16,.10,m,steam)}steam.visible=false;
const objects=new Map<string,THREE.Group>(),start=new Map<string,THREE.Vector3>();const labelTextures:THREE.Texture[]=[];
function label(text:string,parent:THREE.Object3D){const c=document.createElement('canvas');c.width=256;c.height=56;const ctx=c.getContext('2d')!;ctx.fillStyle='#fffdf1';ctx.beginPath();ctx.roundRect(1,1,254,54,14);ctx.fill();ctx.fillStyle='#294b34';ctx.font='600 23px Arial';ctx.textAlign='center';ctx.fillText(text,128,36);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;labelTextures.push(tex);const m=new THREE.SpriteMaterial({map:tex,depthTest:false});materials.push(m);const sprite=new THREE.Sprite(m);sprite.scale.set(1.13,.25,1);sprite.position.set(0,.025,.48);parent.add(sprite);return sprite}
ingredients.forEach((item,i)=>{const g=new THREE.Group();g.userData.id=item.id;g.position.set(-4.05+(i%7)*1.35,.25,.7+Math.floor(i/7)*1.62);start.set(item.id,g.position.clone());scene.add(g);objects.set(item.id,g);const im=mat(item.color);cyl(.48,.34,.19,white,g,0,.10,0);cyl(.414,.414,.015,im,g,0,.202,0);
if(['beras','garam','gula','kacang','bilis'].includes(item.id)){for(let k=0;k<18;k++){const a=k*2.4,r=.31*Math.sqrt((k+.5)/18);const o=ell(item.id==='bilis'?.125:.065,.035,item.id==='beras'?.025:.04,im,g,r*Math.cos(a),.23,r*Math.sin(a));o.rotation.y=k;}}
else if(item.id==='pandan'){for(let k=0;k<3;k++){const leaf=ell(.07,.018,.4,im,g,(k-1)*.1,.25,0);leaf.rotation.y=(k-1)*.3}}
else if(item.id==='telur'){ell(.15,.19,.15,im,g,-.16,.32,0);ell(.15,.19,.15,im,g,.16,.32,.04)}
else if(item.id==='timun'){const cu=ell(.15,.13,.37,im,g,0,.3,0);cu.rotation.y=.5;const sl=cyl(.14,.14,.06,mat('#d3e594'),g,.25,.27,.1);sl.rotation.z=.4;}label(item.name,g)});
const halo=mesh(new THREE.TorusGeometry(.53,.027,8,48),mat('#efb942'),scene);halo.rotation.x=Math.PI/2;
let selected='beras',dragging:string|null=null,down=new THREE.Vector2(),didMove=false,cooking=false,disposed=false,stage=0,station='pot',autoRotate=false;
const dishObjects=new Map<string,THREE.Group>(),dishStarts=new Map<string,THREE.Vector3>();let plated:string[]=[];
const loading=new AbortController();
fetch('/hidangan.json',{signal:loading.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(raw=>{const data=raw as Record<string,{p:number[];c:number[];home:number[]}>;if(disposed)return;Object.entries(data).forEach(([id,item])=>{const g=new THREE.Group();g.userData.id=id;g.userData.radius=id==='nasi'?.49:id==='sambal'?.36:id==='timun'?.39:.40;const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(item.p,3));const colors=item.c.slice();for(let i=0;i<colors.length;i+=3){const color=new THREE.Color().setRGB(colors[i],colors[i+1],colors[i+2],THREE.SRGBColorSpace);colors[i]=color.r;colors[i+1]=color.g;colors[i+2]=color.b}geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();const m=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.8});materials.push(m);mesh(geometry,m,g);g.position.set(2.7+item.home[0],.37,-1.8+item.home[2]);g.visible=plated.includes(id);scene.add(g);dishObjects.set(id,g);dishStarts.set(id,g.position.clone())});hooks.ready?.()}).catch(e=>{if(e.name!=='AbortError')hooks.error?.('Hidangan 3D gagal dimuatkan. Muat semula halaman untuk mencuba lagi.')});
function current(){return stage>=6?dishObjects:objects}
function clampPosition(o:THREE.Group,x:number,z:number){if(stage>=6){const dx=x-2.7,dz=z+1.8,r=1.35-(o.userData.radius??.4),length=Math.hypot(dx,dz),k=length>r?r/length:1;o.position.x=2.7+dx*k;o.position.z=-1.8+dz*k}else{o.position.x=THREE.MathUtils.clamp(x,-4.7,4.7);o.position.z=THREE.MathUtils.clamp(z,-.4,3.4)}}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-.25),hit=new THREE.Vector3(),offset=new THREE.Vector3();
function select(id:string){selected=id;const g=current().get(id);if(!g||!g.visible){halo.visible=false;return}halo.visible=true;halo.position.copy(g.position);halo.position.y=stage>=6?.385:.265;halo.scale.setScalar(stage>=6?.76:1)}select('beras');
function coords(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera)}
function pointerDown(e:PointerEvent){if(e.button!==0)return;coords(e);const hits=raycaster.intersectObjects([...current().values()].filter(g=>g.visible),true);if(!hits.length)return;let root:THREE.Object3D|null=hits[0].object;while(root&&!root.userData.id)root=root.parent;if(!root)return;dragging=root.userData.id;select(dragging!);hooks.select(dragging!);autoRotate=false;controls.enabled=false;down.set(e.clientX,e.clientY);didMove=false;plane.constant=stage>=6?-.37:-.25;raycaster.ray.intersectPlane(plane,hit);offset.copy(root.position).sub(hit);renderer.domElement.setPointerCapture(e.pointerId);e.stopImmediatePropagation()}
function pointerMove(e:PointerEvent){if(!dragging)return;coords(e);if(raycaster.ray.intersectPlane(plane,hit)){const o=current().get(dragging)!;clampPosition(o,hit.x+offset.x,hit.z+offset.z);select(dragging);if(down.distanceTo(new THREE.Vector2(e.clientX,e.clientY))>5)didMove=true}e.stopImmediatePropagation()}
function pointerUp(){if(dragging&&didMove)hooks.move(dragging);dragging=null;controls.enabled=true}
renderer.domElement.addEventListener('pointerdown',pointerDown,true);renderer.domElement.addEventListener('pointermove',pointerMove,true);renderer.domElement.addEventListener('pointerup',pointerUp,true);renderer.domElement.addEventListener('pointercancel',pointerUp,true);
function resetCamera(){autoRotate=false;if(stage>=6){camera.position.set(2.7,5.4,4.3);controls.target.set(2.7,.5,-1.8);controls.minDistance=3;controls.maxDistance=16}else{const k=Math.max(1,1.04/camera.aspect);camera.position.set(0,12*k,14*k);controls.target.set(0,.5,0);controls.minDistance=8;controls.maxDistance=40}controls.update()}
const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();resetCamera()});resize.observe(host);
const flights:{g:THREE.Group;from:THREE.Vector3;to:THREE.Vector3;at:number}[]=[];
let raf=0,lastTime=0,stirUntil=0;function frame(t:number){if(disposed)return;if(autoRotate){const dt=Math.min(.05,(t-lastTime)/1000),v=camera.position.clone().sub(controls.target);v.applyAxisAngle(new THREE.Vector3(0,1,0),dt*.28);camera.position.copy(controls.target).add(v)}lastTime=t;controls.update();spoon.visible=stage===2&&(cooking||t<stirUntil);if(spoon.visible){spoon.rotation.y=t*.006;panBits.rotation.y=t*.001;}if(cooking){steam.children.forEach((s,i)=>{const n=(t*.00035+i/10)%1;s.position.set((station==='pan'?-1.4:-3.65)+Math.sin(i*5+n)*.3,1.1+n*1.6,-2+Math.cos(i*3)*.3);s.scale.setScalar(.5+n)});flame.scale.setScalar(1+Math.sin(t*.008)*.05)}
for(let i=flights.length-1;i>=0;i--){const f=flights[i],p=Math.min(1,(t-f.at)/700);f.g.position.lerpVectors(f.from,f.to,p);f.g.position.y+=Math.sin(p*Math.PI)*1.8;f.g.scale.setScalar(1-p*.7);if(p===1){scene.remove(f.g);flights.splice(i,1)}}renderer.render(scene,camera);raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);
return {select,resetCamera,rotateSelected(){const g=current().get(selected);if(g?.visible)g.rotation.y+=Math.PI/4},moveSelected(dx:number,dz:number){const g=current().get(selected);if(!g?.visible)return;clampPosition(g,g.position.x+dx,g.position.z+dz);select(selected);hooks.move(selected)},arrange(){objects.forEach((g,id)=>{g.position.copy(start.get(id)!);g.rotation.y=0});dishObjects.forEach((g,id)=>{g.position.copy(dishStarts.get(id)!);g.rotation.y=0});select(selected)},setCooking(active:boolean,target='pot'){station=target;cooking=active;steam.visible=active;flame.visible=active;flame.position.x=target==='pan'?-1.4:-3.65},sync(nextStage:number,added:string[],placed:string[],cut:number){const changed=stage!==nextStage;stage=nextStage;plated=placed;objects.forEach(g=>g.visible=stage<6);dishObjects.forEach((g,id)=>g.visible=stage>=6&&plated.includes(id));prepared.visible=stage===5&&added.includes('timun');wholeCucumber.visible=cut===0;slices.forEach((g,i)=>g.visible=i<cut);potFill.visible=stage===1&&added.length>0;eggs.visible=stage===4&&added.includes('telur');panFill.visible=stage===2&&added.length>0;panBits.visible=stage===3&&added.length>0;if(changed)resetCamera();select(selected)},addIngredient(id:string){const source=objects.get(id);if(!source)return;const g=source.clone(true);g.children.filter(c=>c instanceof THREE.Sprite).forEach(c=>g.remove(c));scene.add(g);const to=stage===5?new THREE.Vector3(0,.4,1.2):new THREE.Vector3(stage===2||stage===3?-1.4:-3.65,.7,-2);flights.push({g,from:source.position.clone(),to,at:performance.now()})},stir(){stirUntil=performance.now()+650},toggleOrbit(){autoRotate=!autoRotate;return autoRotate},getPositions(){return Object.fromEntries([...current()].filter(([,g])=>g.visible).map(([id,g])=>[id,{x:g.position.x,z:g.position.z,rotation:g.rotation.y}]))},moveItem(id:string,x:number,z:number){const g=current().get(id);if(!g?.visible)throw Error('Bahan tidak tersedia.');clampPosition(g,x,z);select(id);hooks.select(id);hooks.move(id);return {x:g.position.x,z:g.position.z}},dispose(){disposed=true;loading.abort();cancelAnimationFrame(raf);resize.disconnect();controls.dispose();renderer.dispose();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());labelTextures.forEach(t=>t.dispose());renderer.domElement.remove()}};
}

