'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ChefHat,RotateCcw,Move,MousePointer2,Utensils,Check,ArrowRight,ArrowLeft,ArrowUp,ArrowDown,Flame,BookOpen,Rotate3D,Star,Droplets} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {createKitchen,type Kitchen} from './kitchen';
import {ingredients,dishes,stages,initialState,transition,type Action} from './recipe';
import {registerKitchenTools} from './webmcp';

export default function Home(){
const mount=useRef<HTMLDivElement>(null),kitchen=useRef<Kitchen|null>(null);
const[state,setState]=useState(initialState),stateRef=useRef(state);const[selected,setSelected]=useState('beras');
const[error,setError]=useState(''),[ready,setReady]=useState(false),[message,setMessage]=useState('Pilih satu bahan untuk memulakan susunan dapur anda.');
const[showRecipe,setShowRecipe]=useState(false),[showReset,setShowReset]=useState(false);
const send=useCallback((action:Action)=>{const before=stateRef.current;const result=transition(before,action);stateRef.current=result.state;setState(result.state);if(result.message)setMessage(result.message);
if(action.type==='add'&&result.state!==before)kitchen.current?.addIngredient(action.id);
if(action.type==='stir'&&result.state!==before)kitchen.current?.stir();
if(action.type==='reset'){kitchen.current?.arrange();setSelected('beras');setShowReset(false)}
if(result.state.stage!==before.stage){const id=result.state.stage>=6?'nasi':stages[result.state.stage].needs[0]||'beras';setSelected(id);setMessage(result.message||stages[result.state.stage].text)}
return result;},[]);
useEffect(()=>{if(!mount.current)return;try{kitchen.current=createKitchen(mount.current,ingredients,{select:setSelected,move:id=>send({type:'move',id}),ready:()=>setReady(true),error:setError})}catch{setError('Paparan 3D tidak dapat dimulakan. Cuba pelayar yang menyokong WebGL.')}return()=>kitchen.current?.dispose()},[send]);
useEffect(()=>{kitchen.current?.sync(state.stage,state.added,state.plated,state.slices);kitchen.current?.select(selected)},[state.stage,state.added,state.plated,state.slices,selected,ready]);
useEffect(()=>{kitchen.current?.setCooking(state.running,state.stage===2||state.stage===3?'pan':'pot');if(!state.running)return;const timer=setInterval(()=>send({type:'tick',seconds:.1}),100);return()=>clearInterval(timer)},[state.running,state.stage,send]);
useEffect(()=>registerKitchenTools({getState:()=>stateRef.current,act:send,getKitchen:()=>kitchen.current}),[send]);
function select(id:string){setSelected(id);kitchen.current?.select(id)}
function add(){send(state.stage===6?{type:'plate',id:selected}:{type:'add',id:selected})}
const step=stages[state.stage],plating=state.stage>=6,items=plating?dishes:ingredients;
const item=items.find(i=>i.id===selected),allAdded=step.needs.every(id=>state.added.includes(id));
const nextAllowed=state.stage===0?state.moved.length>=3:state.stage===6?state.plated.length===6:state.complete;
const selectedAvailable=!plating||state.plated.includes(selected);
const canAdd=plating?state.stage===6&&ready&&!state.plated.includes(selected):state.stage>0&&!state.running&&!state.complete&&!state.added.includes(selected);
const addLabel=plating?'Letak di pinggan':state.stage===5?'Bawa ke papan':state.stage===2||state.stage===3?'Masukkan ke kuali':'Masukkan ke periuk';
return <main className="game"><header className="topbar"><div className="brand"><span className="brand-icon"><ChefHat size={24}/></span><div><h1>Dapur Nasi Lemak</h1><p>MASAK · SUSUN · HIDANG</p></div></div><span className="servings">Resipi untuk 2 orang</span><button className="quiet" onClick={()=>setShowRecipe(true)}><BookOpen size={17}/> Resipi</button><button className="quiet" onClick={()=>setShowReset(true)} aria-label="Mula semula permainan"><RotateCcw size={17}/><span className="reset-label"> Mula semula</span></button></header>
<div className="workspace"><aside className="recipe"><span className="eyebrow">{state.stage===7?'SELAMAT MENJAMU SELERA':'DAPUR ANDA, CARA ANDA'}</span><h2>{state.stage===0?<>Mari sediakan<br/>nasi lemak.</>:step.title}</h2><div className="progress-label"><span>{state.stage===7?'Semua langkah selesai':`Langkah ${state.stage+1} daripada 7`}</span><span>{Math.round(Math.min(7,state.stage)/7*100)}%</span></div><Progress value={Math.min(7,state.stage)/7*100} aria-label="Kemajuan memasak"/>
<div className="step-card"><span className="step-no">{state.stage===7?<Check size={28}/>:String(state.stage+1).padStart(2,'0')}</span><h3>{state.stage===0?step.title:state.stage===7?'Chef nasi lemak':'Misi anda'}</h3><p>{step.text}</p></div>
{state.stage===0&&<div className="checklist"><CheckLine done={state.moved.length>=3} text={`${Math.min(3,state.moved.length)} / 3 bahan sudah dialihkan`}/></div>}
{step.needs.length>0&&<div className="checklist" aria-label="Bahan untuk langkah ini">{step.needs.map(id=><CheckLine key={id} done={state.added.includes(id)} text={ingredients.find(i=>i.id===id)!.name}/>)}</div>}
{state.stage===6&&<div className="checklist">{dishes.map(i=><CheckLine key={i.id} done={state.plated.includes(i.id)} text={i.name}/>)}</div>}
{state.stage===7&&<><div className="stars" aria-label="Tiga bintang"><Star fill="currentColor"/><Star fill="currentColor"/><Star fill="currentColor"/></div><p className="muted">7 langkah diselesaikan. 6 komponen lengkap. Satu hidangan hasil kreativiti anda.</p></>}
<div className="action-stack">
{state.stage===1&&!state.washed&&<button className="primary" onClick={()=>send({type:'wash'})}><Droplets size={17}/> Bilas & toskan beras</button>}
{state.stage===2&&!state.complete&&!state.running&&<button className="quiet" disabled={!allAdded||state.stirs>=3} onClick={()=>send({type:'stir'})}>Kacau sambal · {state.stirs}/3</button>}
{state.stage===5&&<>{!state.washed?<button className="primary" disabled={!state.added.includes('timun')} onClick={()=>send({type:'wash'})}><Droplets size={17}/> Basuh timun</button>:<button className="primary" disabled={state.complete} onClick={()=>send({type:'slice'})}>Potong timun · {state.slices}/4</button>}</>}
{step.duration>0&&!state.complete&&<button className="primary" disabled={!allAdded||state.running||(state.stage===2&&state.stirs<3)} onClick={()=>send({type:'cook'})}><Flame size={17}/>{state.running?'Sedang memasak…':step.action}</button>}
{state.running&&<div><div className="heat"><span>Api {state.stage===2?'kecil':'sederhana'}</span><span>{Math.ceil((1-state.progress)*step.duration)} saat</span></div><Progress value={state.progress*100} aria-label="Proses memasak"/></div>}
{!state.running&&state.stage<7&&<button className={state.complete||state.stage===0||state.stage===6?'primary':'quiet'} disabled={!nextAllowed||(state.stage===5&&!ready)} onClick={()=>send({type:'next'})}>{state.stage===0?'Mula memasak':state.stage===6?'Hidangkan nasi lemak':state.stage===4?'Kupas, belah & teruskan':'Langkah seterusnya'}<ArrowRight size={17}/></button>}
{state.stage===7&&<button className="primary" onClick={()=>send({type:'reset'})}><RotateCcw size={17}/> Main sekali lagi</button>}
</div><output className="status" aria-live="polite" aria-atomic="true">{message}</output><div className="recipe-note"><Utensils size={18}/><p>{step.tip}</p></div><p className="footer-note">Masa memasak dipercepat dalam permainan.</p></aside>
<section className="stage" aria-label="Ruang dapur 3D"><div className="scene" ref={mount} tabIndex={0} role="application" aria-label="Dapur 3D. Pilih bahan dalam senarai. Kekunci anak panah untuk alih, R untuk putar, Enter untuk masukkan bahan." onKeyDown={e=>{const dirs:Record<string,[number,number]>={ArrowLeft:[-.18,0],ArrowRight:[.18,0],ArrowUp:[0,-.18],ArrowDown:[0,.18]};if(dirs[e.key]){e.preventDefault();kitchen.current?.moveSelected(...dirs[e.key])}if(e.key.toLowerCase()==='r'){e.preventDefault();kitchen.current?.rotateSelected()}if(e.key==='Enter'&&canAdd){e.preventDefault();add()}}}/>
<div className="scene-heading"><span className="live-dot"/>{plating?'Hidangan anda':'Dapur 3D'}<span>360°</span></div><div className="stage-actions"><button className="quiet" onClick={()=>kitchen.current?.resetCamera()} aria-label="Kembalikan sudut kamera asal"><RotateCcw size={16}/></button><button className="quiet" onClick={()=>{const on=kitchen.current?.toggleOrbit();setMessage(on?'Kamera berputar. Tekan butang putaran sekali lagi untuk berhenti.':'Putaran kamera dihentikan.')}} aria-label="Hidupkan atau hentikan putaran kamera"><Rotate3D size={18}/></button></div>
<div className="camera-help"><Move size={16}/><span>Seret {plating?'lauk':'bahan'} untuk alih · Seret ruang kosong untuk pusing · Skrol untuk zum</span></div>
{error&&<div className="error" role="alert">{error}<button className="quiet" onClick={()=>location.reload()}>Cuba lagi</button></div>}
<div className="selection"><div><small>{plating?'LAUK DIPILIH':'BAHAN DIPILIH'}</small><strong>{item?.name||'Pilih bahan'}</strong></div><div className="tool-actions"><button className="quiet" disabled={!selectedAvailable} aria-label="Alih ke kiri" onClick={()=>kitchen.current?.moveSelected(-.18,0)}><ArrowLeft size={16}/></button><button className="quiet" disabled={!selectedAvailable} aria-label="Alih ke belakang" onClick={()=>kitchen.current?.moveSelected(0,-.18)}><ArrowUp size={16}/></button><button className="quiet" disabled={!selectedAvailable} aria-label="Alih ke depan" onClick={()=>kitchen.current?.moveSelected(0,.18)}><ArrowDown size={16}/></button><button className="quiet" disabled={!selectedAvailable} aria-label="Alih ke kanan" onClick={()=>kitchen.current?.moveSelected(.18,0)}><ArrowRight size={16}/></button><button className="quiet" disabled={!selectedAvailable} aria-label="Putar bahan 45 darjah" onClick={()=>kitchen.current?.rotateSelected()}><RotateCcw size={16}/></button></div>{state.stage>0&&state.stage<7&&<button className="primary" disabled={!canAdd} onClick={add}>{plating&&state.plated.includes(selected)?'Sudah di pinggan':!plating&&state.added.includes(selected)?'Sudah dimasukkan':addLabel}<ArrowRight size={16}/></button>}</div></section>
<aside className="pantry"><div className="pantry-head"><h2>{plating?'Lauk siap dimasak':'Bahan-bahan'}</h2><span>{items.length}</span></div><p className="muted">{plating?'Pilih lauk, letak dan susun di pinggan.':'Pilih bahan untuk alih atau masukkan.'}</p><div className="ingredient-list">{items.map(i=>{const used=plating?state.plated.includes(i.id):state.added.includes(i.id);return <button key={i.id} onClick={()=>select(i.id)} aria-pressed={selected===i.id} className={'ingredient '+(selected===i.id?'chosen ':'')+(used?'used ':'')+(step.needs.includes(i.id)&&!used?'required':'')}><span className="swatch" style={{background:i.color}}/><span><strong>{i.name}</strong><small>{used?(plating?'Di pinggan':'Sudah dimasukkan'):i.amount}</small></span>{used?<Check size={16}/>:<MousePointer2 size={15}/>}</button>})}</div><p className="inventory-caption">{plating?'Susunan hidangan boleh diubah sesuka hati.':'Tanda emas: bahan diperlukan pada langkah ini.'}</p><button className="quiet arrange" onClick={()=>{kitchen.current?.arrange();setMessage('Susunan dikembalikan ke kedudukan asal.')}}><Move size={16}/> Susunan asal</button></aside></div>
<Dialog open={showRecipe} onOpenChange={setShowRecipe}><DialogContent showCloseButton={false} className="game-dialog recipe-dialog"><DialogTitle>Resipi nasi lemak</DialogTitle><DialogDescription>Bahan dan langkah asas untuk 2 orang.</DialogDescription><div className="recipe-scroll"><img className="recipe-image" src="/nasi-lemak.png" alt="Model nasi lemak lengkap dengan sambal, telur, ikan bilis, kacang dan timun"/><h3>Bahan-bahan</h3><dl>{ingredients.map(i=><div key={i.id}><dt>{i.name}</dt><dd>{i.amount}</dd></div>)}</dl><h3>Cara memasak</h3><ol>{stages.slice(1,6).map(i=><li key={i.short}><strong>{i.title}.</strong> {i.tip}</li>)}<li>Hidangkan nasi bersama sambal, ikan bilis, kacang, telur dan timun.</li></ol></div><button className="primary" onClick={()=>setShowRecipe(false)}>Kembali ke dapur</button></DialogContent></Dialog>
<AlertDialog open={showReset} onOpenChange={setShowReset}><AlertDialogContent className="game-dialog"><AlertDialogTitle>Mula semula?</AlertDialogTitle><AlertDialogDescription>Kemajuan memasak dan susunan bahan akan dikembalikan ke permulaan.</AlertDialogDescription><button className="primary" onClick={()=>send({type:'reset'})}>Ya, mula semula</button><button className="quiet" onClick={()=>setShowReset(false)}>Sambung memasak</button></AlertDialogContent></AlertDialog>
</main>;
}
function CheckLine({done,text}:{done:boolean;text:string}){return <div className={'check-item '+(done?'done':'')}><span className="check-circle">{done&&<Check size={12}/>}</span><span>{text}</span></div>}
