import type {GameState,Action} from './recipe';
import type {Kitchen} from './kitchen';
type Context={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};
export function registerKitchenTools(api:{getState:()=>GameState;act:(action:Action)=>{state:GameState;message:string};getKitchen:()=>Kitchen|null}){
const ctx=(document as Document&{modelContext?:Context}).modelContext;if(!ctx?.registerTool)return ()=>{};
const lifecycle=new AbortController();const register=(tool:Record<string,unknown>)=>{try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
register({name:'read_kitchen_state',title:'Lihat keadaan dapur',description:'Read cooking progress and positions of available ingredients or plated dishes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({game:api.getState(),positions:api.getKitchen()?.getPositions()})});
register({name:'arrange_kitchen_ingredients',title:'Susun bahan dapur',description:'Move available ingredients or plated dishes on the same 3D surface used by the player. Does not add ingredients to cooking or complete a step.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:14,items:{type:'object',properties:{id:{type:'string'},x:{type:'number'},z:{type:'number'}},required:['id','x','z'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const data=input as {items?:{id:string;x:number;z:number}[]};const kitchen=api.getKitchen();if(!kitchen||!Array.isArray(data?.items)||data.items.length<1||data.items.length>14)throw Error('Senarai bahan tidak sah.');const available=kitchen.getPositions();if(data.items.some(i=>!i||typeof i.id!=='string'||!available[i.id]||!Number.isFinite(i.x)||!Number.isFinite(i.z)))throw Error('Bahan atau kedudukan tidak sah.');data.items.forEach(i=>kitchen.moveItem(i.id,i.x,i.z));await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {positions:kitchen.getPositions(),game:api.getState()}}});
return ()=>lifecycle.abort();
}
